// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjAxcbhmHE8EsIj7NEufGm7EZzZ27SIoY',
    appId: '1:65328278827:web:dc0f8fd0ea7e7a5643e96e',
    messagingSenderId: '65328278827',
    projectId: 'capston-d8591',
    authDomain: 'capston-d8591.firebaseapp.com',
    storageBucket: 'capston-d8591.appspot.com',
    measurementId: 'G-93VGH7QXNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8OGReIzVQfudYbjJOoYHAcr3_cmz7Emk',
    appId: '1:65328278827:android:6174f7b65c479cf843e96e',
    messagingSenderId: '65328278827',
    projectId: 'capston-d8591',
    storageBucket: 'capston-d8591.appspot.com',
  );
}
